### ISSUE TITLE
Images that do not open in litebox on this page:

### ISSUE THREAD

**Issue by jschneid177** [schneidan/schneidan#11]
http://schneidan.com/2015/02/27/in-my-little-camera-bag-yashica-electro-35-gsn/

http://schneidan.com/2015/03/05/in-my-little-camera-bag-no-4-zeiss-ikon-colora-f/

http://schneidan.com/2015/03/11/in-my-little-camera-bag-no-5-pentax-spotmatic-sp1000/in-bag-5-spotmatic-angle/

http://schneidan.com/2015/03/19/in-my-little-camera-bag-no-6-akameter-and-takumar-50mm-f1-4/in-bag-6-takumar-lenses/

There are surely more - you need to check

**Comment by schneidan** [comment]
All appear to work.

**Comment by jschneid177** [comment]
Are they all supposed to be an endless loop, or should they stop at the last photo and only have a back arrow??

**Comment by schneidan** [comment]
Endless loop.
