### ISSUE TITLE
Photo on page noted is very small - opens bigger in lite box

### ISSUE THREAD

**Issue by jschneid177** [schneidan/schneidan#13]
http://schneidan.com/2011/01/18/calliandra-surinamensis-the-pink-powder-puff/

**Comment by jschneid177** [comment]
Similar issue on http://schneidan.com/2011/02/22/sunset-shone-in-the-facets-of-albedo/

Also note presence of <em></em> tags and other HTML tags visible in caption on this page

**Comment by jschneid177** [comment]
Also on http://schneidan.com/2010/12/30/hand-tinted-lights-in-the-budding-snowstorm/

**Comment by jschneid177** [comment]
http://schneidan.com/2010/12/15/butterfly-the-wings-move-actually/

**Comment by jschneid177** [comment]
http://schneidan.com/2010/12/30/hand-tinted-lights-in-the-budding-snowstorm/

**Comment by schneidan** [comment]
All fixed.
